import Head from 'next/head'
import Banner from './component/Banner'
import About from './component/About'
import ScrollBox from './component/ScrollBox'
import Services from './component/Services'
import Footer from './component/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>all in one agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/all-in-one-icone.ico" />
      </Head>
      <Banner/>
      <About/>
      <ScrollBox/>
      <Services/>
      <Footer/>
      
    </>
  )
}
